config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#new'
    get 'users/new2', to: 'devise/registrations#new2', as: :sms_send_user_registration
    post 'users/new2(.:format)', to: 'devise/registarations#new2'
    get 'users/new2_2', to: 'devise/registrations#new2_2', as: :sms_receive_user_registration
    post 'users/new2_2(.:format)', to: 'devise/registarations#new2_2'
    get 'users/new3', to: 'devise/registrations#new3', as: :personal_information_user_registration
    post 'users/new3(.:format)', to: 'devise/registarations#new3'
    get 'users/new4', to: 'devise/registrations#new4', as: :credit_user_registration
    post 'users/new4(.:format)', to: 'devise/registarations#new4'
    get 'users/new5', to: 'devise/registrations#new5', as: :sinup_user_registration
    post 'users/new5(.:format)', to: 'devise/registarations#new5'
  end

  
  resources :products, only: [:new, :create, :show] do
    member do
      post "purchase"
    end
  end


  resources :credit_cards, only: [:new, :show] do
    collection do
      get 'registration'
    end
  end

  resources :users, only: [:show] do
    member do
      get "likes", "listings", "in_progress", "completed", "purchase", "purchased"

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/personal_information.rb
class PersonalInformation < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  has_one :personal_information
  accepts_nested_attributes_for :personal_information
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, personal_information_attributes: [:last_name, :first_name, :last_name_k, :first_name_k, :birthday, :user_id] ])
  end

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  def new
    
  end

  def show
    
  end

  def registration
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def new
    @product = Product.new
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    @user = User.new
    @user.build_personal_information
  end

  def new2
  end

  def new2_2
  end

  def new3
  end

  def new4
    @credit_card = Credit_card.new
  end

  def new5
  end

  private 
  def user_params
    params.require(:user).permit(
      :nickname, 
      :email, 
      :password, 
      :password_confirmation 
    )
  end
  def personal_informations
    params.require(:personal_information).permit(
      :last_name, 
      :first_name, 
      :last_name_k, 
      :first_name_k
    )
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def likes
    likes = current_user.likes
    @products = likes.map(&:product)
  end

  def listings
    @products = current_user.products.where(transaction_status: 'listing')
  end

  def in_progress
    @products = current_user.products.where(transaction_status: 'in_progress')
  end

  def completed
    @products = current_user.products.where(transaction_status: 'completed')
  end

  def purchase
    @products = Product.is_purchased(current_user.id)
                       .where(transaction_status: 'in_progress')
  end

  def purchased
    @products = Product.is_purchased(current_user.id)
                       .where(transaction_status: 'completed')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/credit_cards/_cardform.html.haml
.form-box
  .form-box__number
    %label.form-box__number__payment カード番号
    %span.form-box__number__require 必須
    = f.text_field :card_number, autofocus: true, autocomplete: "off", placeholder: "半角数字のみ",maxlength: "19", class: "form-box__number__input", required: true
    %ul.form-box__number__card-list
      %li.form-box__number__card-list__visa
        = image_tag "visa.svg", alt: "icon", height: "20", width: "49"
      %li.form-box__number__card-list__master
        = image_tag "master-card.svg", alt: "icon", height: "20", width: "34"
      %li.form-box__number__card-list__saison
        = image_tag "saison-card.svg", alt: "icon", height: "20", width: "30"
      %li.form-box__number__card-list__jcb
        = image_tag "jcb.svg", alt: "icon", height: "20", width: "32"
      %li.form-box__number__card-list__american
        = image_tag "american_express.svg", alt: "icon", height: "20", width: "21"
      %li.form-box__number__card-list__diners
        = image_tag "dinersclub.svg", alt: "icon", height: "20", width: "32"
      %li.form-box__number__card-list__discover
        = image_tag "discover.svg", alt: "icon", height: "20", width: "32"
  .form-box__signup 
    %label.form-box__signup__expire 有効期限
    %span.form-box__signup__require 必須
    %br
    != sprintf(f.date_select(:expiration_date_d,with_css_classes:'form-box__signup__year', order:[:month,:year,:day], use_month_numbers:true, discard_day:true, start_year:Time.now.year-2000, end_year:Time.now.year-2000+10, date_separator:'%s'),'月') + '年'
  .form-box__security
    %label.form-box__security__code セキュリティコード
    %span.form-box__security__require 必須
    = f.text_field :security_code, autofocus: true, autocomplete: "off", placeholder: "カード背面４桁もしくは３桁の番号", class: "form-box__security__input", required: true
    .form-box__security__info
      %span.form-box__security__info__question ？

      カード裏面の番号とは?

app/views/credit_cards/new.html.haml
= render "shared/header"
.main
  .contents
    = render "users/leftcontent"

.content  
  .content__chapter
    %h2.content__chapter__head
      クレジットカード情報入力
      %form.content__chapter__form
    = render "cardform"
      %button#submit-button.form-box__btn 追加する
= render "shared/purchaseBtn"
= render "shared/banner"
= render "shared/footer"

app/views/credit_cards/registration.html.haml
= render "shared/header"
.main
  .contents
    = render "users/leftcontent"
    .content  
      .content__chapter
        %h2.content__chapter__head
          支払い方法
        .card-index
          %section.card-index__title
            .card-index__title__head
              %h3.card-index__title__head__sub クレジットカード一覧
          %section.card-index__add
            .card-index__add__card
              = link_to "", class: "card-index__add__card__button" do
                %i.fa.fa-credit-card
                  クレジットカードを追加する
          .card-index__regist
            = link_to "", class: "card-index__regist__link" do
              %span.card-index__regist__link__text 支払い方法について
              %i.fa.fa-chevron-right

= render "shared/purchaseBtn"
= render "shared/banner"

= render "shared/footer"

app/views/credit_cards/show.html.haml
= render "shared/header"
.main
  .contents
    = render "users/leftcontent"
    .content  
      .content__chapter
        %h2.content__chapter__head
          支払い方法
        .card-index
          %section.card-index__title
            .card-index__title__head
              %h3.card-index__title__head__sub クレジットカード一覧
            %ul.card-index__title__list
              %li.card-detail
                %form.card-detail__form
                  %figure
                    = image_tag "visa.svg", alt: "icon", height: "15", width: "49"
                  .card-detail__form__num ************1234
                  .card-detail__form__limit-num 12/20
                  %button.card-detail__form__button{type: "submit"} 削除する

          .card-index__regist
            = link_to "", class: "card-index__regist__link" do
              %span.card-index__regist__link__text 支払い方法について
              %i.fa.fa-chevron-right

= render "shared/purchaseBtn"
= render "shared/banner"
= render "shared/footer"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreemarketSample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/show.html.haml
= render "shared/header"
%nav.breadCrumbs
  %ul
    %li
      = link_to "メルカリ", root_path
    %li
      = fa_icon "angle-right"
    %li
      = link_to "hoge", ""
    %li
      = fa_icon "angle-right"
    %li
      = link_to "fuga", ""
    %li
      = fa_icon "angle-right"
    %li
      = link_to "piyo", ""
    %li
      = fa_icon "angle-right"
    %li
      %p 名前
.main
  .showMain
    .contentLeft
      = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
        = image_tag"side_banner.jpg", size: "280x238"
    .contentRight
      .topContent
        .itemBox
          %h2.itemBox__name 商品名
          .itemBox__body
            %ul
              %li
                = image_tag"", size: "300x285"
                .soldout
                .soldoutText 売り切れ
                %ul
                  %li
                    = image_tag "", size: "75x75"
              %li.table
                %table
                  %tbody
                    %tr
                      %th 出品者
                      %td だれ誰
                    %tr
                      %th カテゴリー
                      %td
                        = link_to "メインカテゴリー", ""
                        %br
                        = link_to "サブカテゴリー", ""
                        %br
                        = link_to "アイテム", ""
                    %tr
                      %th ブランド
                      %td
                        = link_to "ブランド名", "#"
                    %tr
                      %th 商品のサイズ
                      %td これくらい
                    %tr
                      %th 商品の状態
                      %td こんなもん
                    %tr
                      %th 配送料の負担
                      %td 100円
                    %tr
                      %th 発送元の地域
                      %td
                        = link_to "青森", ""
                    %tr
                      %th 発送日の目安
                      %td 3日
          .itemBox__price
            %span
              4000円
            %span
              (税込)
            %span
              送料込み
            -# 購入ボタンはつけてください
          .itemDetail 詳細情報
          %ul
            - if user_signed_in?
              %li.optionalBtn.likeBtn.likeBtn--red{id: "unlikeBtn"}
                = fa_icon "heart", text: "いいね 1", id: ""
              -# %li.optionalBtn.likeBtn{id: "likeBtn"}
              -#   = fa_icon "heart", text: "いいね #{@product.like_count}"
            %li.optionalBtn
              = link_to "#" do
                = fa_icon "flag", text: "不適切な商品の通報"
            %li.optionalBtn
              = link_to "#" do
                = fa_icon "lock", text: "あんしん・あんぜんへの取り組み"
        -# - if user_signed_in?
        -#   .commentBox
        -#     - if @comments
        -#       %ul.commentContents
        -#         - @comments.each do |comment|
        -#           %li.commentContent
        -#             .commentUser
        -#               = link_to user_path(comment.user) do
        -#                 %figure
        -#                   = image_tag "member_photo_noimage_thumb.png"
        -#                 %p.userName #{comment.user.nickname}
        -#             .commentBody
        -#               .commentBody__text
        -#                 %p #{comment.body}
        -#               %ul.commentBody__time
        -#                 = content_tag(:li, fa_icon("clock-o", text: "#{comment.created_date}"))
        -#                 %li
        -#                   %ul.optionBtns
        -#                     - if user_signed_in? && comment_ownner?(comment)
        -#                       %li
        -#                         = link_to "/products/#{comment.product.id}/comments/#{comment.id}", method: :DELETE, id: "delete--comment" do
        -#                           = fa_icon"trash", class: "optionBtn"
        -#                       %li
        -#                         = link_to product_comment_path(@product, comment), method: :PATCH, id: "edit--comment" do
        -#                           = fa_icon"edit", class: "optionBtn"
        -#                     %li
        -#                       = link_to "#" do
        -#                         = fa_icon"flag"
        -#     %p.noticeMsg
        -#       相手のことを考え丁寧なコメントを心がけましょう。
        -#       %br
        -#       不快な言葉遣いなどは利用制限や退会処分となることがあります。
        -#     - if current_user
        -#       = form_for [@product, @comment] do |f|
        -#         = f.text_area :body, required: true
        -#         %br
        -#         = button_tag type: "submit", class: "commentBtn" do
        -#           = fa_icon "comment", text: "コメントする"
      %ul.links
        %li
          = link_to "#" do
            = fa_icon "angle-left"
            %span
            前の商品
        %li
          = link_to "#" do
            %span 後ろの商品
            = fa_icon "angle-right"
      .relatedItems
        = link_to "カテゴリをもっと見る", ""

= render "shared/banner"
= render "shared/footer"
= render "shared/purchaseBtn"

app/views/shared/_banner.html.haml
%aside.appBanner
  .inner
    %h2.inner__title スマホでかんたんフリマアプリ
    %p.inner__text 今すぐ無料ダウンロード！
    .inner__icon
      = image_tag"mercari_icon.png", size: "68x68"
      = link_to image_tag("app-store.svg", size: "133x40", class: "linkIcon aBtn"), "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8"
      = link_to image_tag("google-play.svg", size: "133x40", class: "linkIcon gBtn"), "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja"
  = image_tag"download_content_pc.png", size: "300x262", class: "bgIcon"

app/views/shared/_header.html.haml
%header.pcHeader
  .headerInner
    .mainHeader.clearfix
      %h1.icon
        = link_to image_tag("logo.svg", size: "134x36"), root_path
      .searchBox
        = form_tag "", method: :get do
          %input.searchBox--input{id: "searchInput", name: "key",placeholder: "キーワードから探す"}
            =button_to type: "submit" do
              =fa_icon "search"
      %ul.resultLists
    .nav.clearfix
      %ul.listsLeft
        %li.listsLeft__item.listsLeft__item--first
          = link_to "カテゴリー", "", {id: "catBtn"}
          .tree.displayNone
            %ul.categoryTree
              - [].each do |category|
                %li.categoryTree--item= link_to "#{category.name}", "", {}
        %li.listsLeft__item
          = link_to "ブランド", "", {id: "brandBtn"}
          %ul.brandsPulldown.displayNone
            - [].each do |brand|
              %li.brandsPulldown--item
                = link_to "", "", {}
      - if user_signed_in?
        %ul.listsRight
          %li.listsRight__item
            = link_to "" do
              = image_tag("member_photo_noimage_thumb.png", size: "32x32",)
              %span マイページ
          %li.listsRight__item
            = link_to "#" do
              = fa_icon "bell", text: "お知らせ"
          %li.listsRight__item
            = link_to "#" do
              = fa_icon "check", text: "やることリスト"
      - else
        %ul.listsRight
          %li.listsRight__item.listsRight__item--login
            = link_to "ログイン", new_user_session_path
          %li.listsRight__item.listsRight__item--new
            = link_to "新規会員登録", new_user_registration_path

app/views/shared/_purchaseBtn.html.haml
= link_to "" do
  .purchaseBtn
    %span.purchaseBtn__text 出品
    =fa_icon "camera", class: "fa-4x purchaseBtn__icon"

= link_to "" do
  .purchaseBtn
    %span.purchaseBtn__text 出品
    = fa_icon "camera", class: "fa-4x purchaseBtn__icon"

app/views/users/_leftcontent.html.haml
.leftContent
  %ul
    %li
      = link_to user_path(current_user) do
        %span マイページ
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span お知らせ
        = fa_icon "angle-right"
    %li
      = link_to likes_user_path(current_user) do
        %span いいね！一覧
        = fa_icon "angle-right"
    %li
      = link_to new_product_path do
        %span 出品する
        = fa_icon "angle-right"
    %li
      = link_to listings_user_path(current_user) do
        %span 出品した商品---出品中
        = fa_icon "angle-right"
    %li
      = link_to in_progress_user_path(current_user) do
        %span 出品した商品---取引中
        = fa_icon "angle-right"
    %li
      = link_to completed_user_path(current_user) do
        %span 出品した商品---売却済
        = fa_icon "angle-right"
    %li
      = link_to purchase_user_path(current_user) do
        %span 購入した商品---取引中
        = fa_icon "angle-right"
    %li
      = link_to purchased_user_path(current_user) do
        %span 購入した商品---過去の取引
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span ニュース一覧
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span 評価一覧
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span ガイド
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span お問い合わせ
        = fa_icon "angle-right"
  %h3 売上・ポイント
  %ul
    %li
      = link_to "#" do
        %span 売上・振込申請
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span ポイント
        = fa_icon "angle-right"
  %h3 設定
  %ul
    %li
      = link_to "#" do
        %span プロフィール
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span 住所変更
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span 支払い方法
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span メール/パスワード
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span 本人情報
        = fa_icon "angle-right"
    %li
      = link_to "#" do
        %span 電話番号の確認
        = fa_icon "angle-right"
    %li
      = link_to destroy_user_session_path, method: :delete do
        %span ログアウト
        = fa_icon "angle-right"
  = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8" do
    = image_tag("side_banner.jpg", size: "280x238")

app/views/users/_product.html.haml
%li.itemList
  = link_to product_path(product) do
    - if product_soldout?(product)
      .soldout--small
      .soldoutText--small 売切
    %figure.iconPic
      = image_tag "#{product.captured_images.first.content}"
    .contents
      .content__body #{product.name}
      .content__price ¥ #{product.price}
    = fa_icon "angle-right", {class: "angleRight"}

app/views/users/completed.html.haml
= render "shared/header"
%nav.breadCrumbs
  %ul
    %li
      = link_to "メルカリ", root_path
    %li
      = fa_icon "angle-right"
    %li
      = link_to " マイページ", user_path(current_user)
    %li
      = fa_icon "angle-right"
    %li
      %p 出品した商品 - 売却済み
.main
  .contents
    = render "leftcontent"
    .rightContent
      %h2.listingsHeader 出品した商品
      %ul.listingsTab
        %li.tabItem
          = link_to "出品中", listings_user_path(current_user)
        %li.tabItem
          = link_to "取引中", in_progress_user_path(current_user)
        %li.tabItem.active
          = link_to "売却済", "#"
      - if @products.empty?
        %ul.itemNotFound
          %li.itemNotFound__text 売却済みの商品がありません
      - else
        %ul.itemLists
          = render partial: "users/product", collection: @products
= render "shared/banner"
= render "shared/footer"
= render "shared/purchaseBtn"

app/views/users/in_progress.html.haml
= render "shared/header"
%nav.breadCrumbs
  %ul
    %li
      = link_to "メルカリ", root_path
    %li
      = fa_icon "angle-right"
    %li
      = link_to " マイページ", user_path(current_user)
    %li
      = fa_icon "angle-right"
    %li
      %p 出品した商品 - 取引中
.main
  .contents
    = render "leftcontent"
    .rightContent
      %h2.listingsHeader 出品した商品
      %ul.listingsTab
        %li.tabItem
          = link_to "出品中", listings_user_path(current_user)
        %li.tabItem.active
          = link_to "取引中", "#"
        %li.tabItem
          = link_to "売却済", completed_user_path(current_user)
      - if @products.empty?
        %ul.itemNotFound
          %li.itemNotFound__text 取引中の商品がありません
      - else
        %ul.itemLists
          = render partial: "users/review", collection: @products, as: "product"
= render "shared/banner"
= render "shared/footer"
= render "shared/purchaseBtn"

app/views/users/likes.html.haml
= render "shared/header"
%nav.breadCrumbs
  %ul
    %li
      = link_to "メルカリ", root_path
    %li
      = fa_icon "angle-right"
    %li
      = link_to "マイページ", user_path(current_user)
    %li
      = fa_icon "angle-right"
    %li
      %p いいね！ 一覧
.main
  .contents
    = render "leftcontent"
    .rightContent
      %h2.likeHeader いいね！ 一覧
      - if @products.empty?
        %ul.itemNotFound
          %li.itemNotFound__text いいね！がありません
      - else
        %ul.itemLists
          = render partial: "users/product", collection: @products
= render "shared/banner"
= render "shared/footer"
= render "shared/purchaseBtn"

app/views/users/listings.html.haml
= render "shared/header"
%nav.breadCrumbs
  %ul
    %li
      = link_to "メルカリ", root_path
    %li
      = fa_icon "angle-right"
    %li
      = link_to " マイページ", user_path(current_user)
    %li
      = fa_icon "angle-right"
    %li
      %p 出品した商品 - 出品中
.main
  .contents
    = render "leftcontent"
    .rightContent
      %h2.listingsHeader 出品した商品
      %ul.listingsTab
        %li.tabItem.active
          = link_to "出品中", "#"
        %li.tabItem
          = link_to "取引中", in_progress_user_path(current_user)
        %li.tabItem
          = link_to "売却済", completed_user_path(current_user)
      - if @products.empty?
        %ul.itemNotFound
          %li.itemNotFound__text 出品中の商品がありません
      - else
        %ul.itemLists
          = render partial: "users/product", collection: @products
= render "shared/banner"
= render "shared/footer"
= render "shared/purchaseBtn"

app/views/users/purchase.html.haml
= render "shared/header"
%nav.breadCrumbs
  %ul
    %li
      = link_to "メルカリ", root_path
    %li
      = fa_icon "angle-right"
    %li
      = link_to " マイページ", user_path(current_user)
    %li
      = fa_icon "angle-right"
    %li
      %p 購入した商品 - 取引中
.main
  .contents
    = render "leftcontent"
    .rightContent
      %h2.listingsHeader 購入した商品
      %ul.listingsTab
        %li.tabItem.tabItem--second.active
          = link_to "取引中", "#"
        %li.tabItem.tabItem--second
          = link_to "過去の取引", purchased_user_path(current_user)
      - if @products.empty?
        %ul.itemNotFound
          %li.itemNotFound__text 取引中の商品がありません
      - else
        %ul.itemLists
          = render partial: "users/review", collection: @products, as: "product"
= render "shared/banner"
= render "shared/footer"
= render "shared/purchaseBtn"

app/views/users/purchased.html.haml
= render "shared/header"
%nav.breadCrumbs
  %ul
    %li
      = link_to "メルカリ", root_path
    %li
      = fa_icon "angle-right"
    %li
      = link_to " マイページ", user_path(current_user)
    %li
      = fa_icon "angle-right"
    %li
      %p 購入した商品 - 過去の取引
.main
  .contents
    = render "leftcontent"
    .rightContent
      %h2.listingsHeader 購入した商品
      %ul.listingsTab
        %li.tabItem.tabItem--second
          = link_to "取引中", purchase_user_path(current_user)
        %li.tabItem.tabItem--second.active
          = link_to "過去の取引", "#"
      - if @products.empty?
        %ul.itemNotFound
          %li.itemNotFound__text 過去の取引がありません
      - else
        %ul.itemLists
          = render partial: "users/product", collection: @products
= render "shared/banner"
= render "shared/footer"
= render "shared/purchaseBtn"